collections_dir: content

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

collections:
  getting-started:
      output: true
  guides:
     output: true
  references:
     output: true
  components:
     output: true
  releases:
     output: true
  comp-releases:
    output: true
  admin:
    output: true

plugins:
  - jekyll-redirect-from

algolia:
  application_id: 'OIJ2XNEVHZ'
  index_name:     'test_elasticio_documentation'
  search_only_api_key: 'e434b9595ab515ca31a23e22aa39ecf1'

exclude:

  - .jekyll-cache
